### ISSUE TITLE
KeyNotFoundException on server deserialization in limited scenarios

### ISSUE THREAD

**Issue by ardave** [Zaid-Ajaj/Fable.Remoting#122]
I have a single-case union like this:

`type RemoteWork = RemoteWork of string`

My Fable/Elmish app has type for ViewModels which collects user input that will eventually wind up as domain entity properties, like this:

```
type RequiredInputItem<'TInput> =
| NoUserInputYet 
| InvalidUserInput of ('TInput * ValidationError)
| ValidUserInput   of 'TInput   

module RequiredInputItem =
    let validOrFail (ii:RequiredInputItem<'TInput>) =
        match ii with
        | NoUserInputYet     -> failwith "No value has been inputted"
        | InvalidUserInput _ -> failwith "Input is not valid!"
        | ValidUserInput x   -> x
```

I map the viewmodel to the domain entity on the client.  The domain entity type is defined in a project which is shared between the client and server.

It is the domain entity that I transmit "over the wire" via Fable.Remoting.  When I map the property from the view model to the domain entity (on the client) like this

```
let myEntity = 
             { RemoteWork         = model.RemoteWork |> RequiredInputItem.validOrFail }

```
... the resulting entity will fail on the server with the exception _System.Collections.Generic.KeyNotFoundException: An index satisfying the predicate was not found in the collection._  I will post the full stack trace at the bottom.

I should note that in the code above, myEntity.RemoteWork is of type RemoteWork, whereas model.RemoteWork is a RequiredInputItem of RemoteWork.

Here's a very strange observation:  When I hard-code a RemoteWork value like this, the deserialization on the server works fine:

```
let myEntity =
    { RemoteWork = RemoteWork "Full Time" }

```
I don't know what the difference could be to Fable.Remoting, as its deserialization occurs a bit downstream in the code.  But there is some sort of problem that manifests itself when Fable.Remoting attempts to deserialize the domain entity as the server receives it.

I do notice some differences in the serialized content, however, as captured using Fiddler.

The first (failing) code snippet above, getting extracting the RemoteWork from the RequiredUserInput<RemoteWork>, results in json like this:

```
	      ],
	      "RemoteWork": "Fully Remote",
	      "InterviewFormats": [
```

whereas the second (succeeding) code snippet above results in json like this:
```
	      ],
	      "RemoteWork": [
	        "RemoteWork",
	        "Fully Remote"
	      ],
	      "InterviewFormats": [
```

I suppose a RemoteWork should be a RemoteWork should be a RemoteWork, no matter how it was constructed, whether hard-coded or the result of a function evaluation, so with any luck I have found a valuable defect and am not just doing something wrong myself.

I am using:
dotnet-fable (2.0.11)
Fable.Core (2.0.3)
Fable.JsonConverter (1.0.8)
Fable.Remoting.Client (4.5.6)
Fable.Remoting.Giraffe (3.6)
Fable.Remoting.Json (2.2)
Fable.Remoting.Server (4.4.1)
Fable.SimpleJson (2.10)
FSharp.Core (4.6.2)

"fable-compiler": {
      "version": "2.2.3"

Please let me know any further information that I can provide.

Here is the full stacktrace:

System.Collections.Generic.KeyNotFoundException: An index satisfying the predicate was not found in the collection.
   at Microsoft.FSharp.Collections.ArrayModule.loop@731-40[T](FSharpFunc`2 predicate, T[] array, Int32 i)
   at Fable.Remoting.Json.FableJsonConverter.ReadJson(JsonReader reader, Type t, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 2159
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 2203
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 1943
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 476
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 2203
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 1943
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 476
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 167
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType) in /_/Src/Newtonsoft.Json/JsonSerializer.cs:line 907
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer) in /_/Src/Newtonsoft.Json/Linq/JToken.cs:line 2070
   at Fable.Remoting.Server.DynamicRecord.createArgsFromJson$cont@132-1(RecordFunctionInfo func, FSharpOption`1 logger, Type input, JToken parsedJson, Unit unitVar)
   at Fable.Remoting.Server.DynamicRecord.tryCreateArgsFromJson(RecordFunctionInfo func, String inputJson, FSharpOption`1 logger)

**Comment by Zaid-Ajaj** [comment]
Hello David, this looks very strange indeed. In the failing case `{  "RemoteWork": "Fully Remote" }` is incorrectly *serialized* from the client as it should have been 
```json
{ "RemoteWork": ["RemoteWork", "Fully Remote"] }
``` 
or 
```json
{ "RemoteWork":  { "RemoteWork": "Fully Remote" } }
```

Two questions come to mind:
- Can I assume that `model.RemoteWork` is of type `RequiredInputItem<RemoteWork>` and not `RequiredInputItem<string>`? (in the latter case it shouldn't be able to compile but just to be sure)

- Can you update `Fable.SimpleJson` to latest 3.1.1-beta?

Thanks for reporting the issue, I will investigate shortly after I am back from work :)

**Comment by Zaid-Ajaj** [comment]
I have added your code sample to the integration tests and everything seems to work just fine using latest versions. 
```
Fable.Remoting.Client 5.3.0-beta
  |-- Fable.SimpleJson 3.1.1-beta

Fable.Remoting.Server 4.4.1

Fable.Remoting.Json 2.20
```

I added these types:
```fs
type RemoteWork = RemoteWork of string 

type RemoteWorkEntity = { RemoteWork : RemoteWork }

type ValidationError = ValidationError of string 

type RequiredInputItem<'TInput> =
    | NoUserInputYet 
    | InvalidUserInput of ('TInput * ValidationError)
    | ValidUserInput   of 'TInput   

module RequiredInputItem =
    let validOrFail (ii:RequiredInputItem<'TInput>) =
        match ii with
        | NoUserInputYet     -> failwith "No value has been inputted"
        | InvalidUserInput _ -> failwith "Input is not valid!"
        | ValidUserInput x   -> x
```

and a function `echoRemoteWorkEntity : RemoteWorkEntity -> Async<RemoteWorkEntity>`
then in my test that works:
```fs
QUnit.testCaseAsync "IServer.echoRemoteWorkEntity" <| fun test ->
    async {
        let entity = { RemoteWork = RequiredInputItem.validOrFail (ValidUserInput (RemoteWork "Fully Remote")) }
        let! echoedEntity = server.echoRemoteWorkEntity entity 
        test.equal true (echoedEntity.RemoteWork = RemoteWork "Fully Remote")
    }
```
> so with any luck I have found a valuable defect and am not just doing something wrong myself.

Maybe it is that you are using incompatible Fable setup? I see you are using `dotnet-fable` where as `fable-compiler` version 2.2.3 works only with fable-loader (via std-in) and Fable.Core 3 beta or later

**Comment by ardave** [comment]
I have a fair amount of hand-written thoth serialization in this same project (used for purposes unrelated to client<->server comms), which looks like it might be broken by moving to these newer *beta packages.  

I might instead look for some time to put together a throwaway project to first duplicate this issue and second, to see what happens when I update it to Fable.SimpleJson 3.1.1-beta.

**Comment by Zaid-Ajaj** [comment]
That sounds like a good idea. Just to be sure, can you please log `myEntity` to the console before sending it to the server to see how it looks like?

**Comment by ardave** [comment]
I have found the source of my troubles, and it was all in code on my end, and not version-dependent. 

Consider the following code:
```
let createRadioGroup dispatch strList groupName wrap onChangeMsg =
    let stringToRadioGroupItem (HtmlEncoded s) =
        div []
            [ input
                [ Type "radio"
                  Name groupName
                  Value s
                  OnClick (fun ev -> !! ev.target?value |> wrap |> onChangeMsg |> dispatch) ]
              label [ ClassName "radio" ][str s]]
    let radioGroupItems = strList |> List.map stringToRadioGroupItem
    radioGroupItems
```

Where `wrap` is the single-case-union (SCU) constructor function for one of any number of such types that I have created to distinguish various types of strings.  OnChangeMsg is the Elmish message that is sent whenever a radio group item is clicked, and that msg requires an argument of the particular SCU type that is created by `wrap`.

Now take away the `wrap` parameter/function altogether and pass the (dynamically-typed) string to the Msg directly.   That's what I had going on.

I would expect this to manifest with some sort of problem downstream in the code execution and indeed, it was pretty far downstream and quite difficult to identify.

But I greatly appreciate your help with it!  Again the project has been an absolute joy to work with.

**Comment by Zaid-Ajaj** [comment]
Indeed this is way far downstream, I am glad to hear that you could find it, must have been tedious! I personally try to avoid any usage of dynamic operators in application code, only in libraries hidden away behind type-safe public APIs. 

In your case, I guess you could use the same string value `s` coming from `HtmlEncoded s` as your input string for the message you wanted to dispatch, i.e.:
```fs
let createRadioGroup dispatch strList groupName wrap onChangeMsg =
    let stringToRadioGroupItem (HtmlEncoded s) =
        div []
            [ input
                [ Type "radio"
                  Name groupName
                  Value s
                  OnClick (fun _ -> s  |> wrap |> onChangeMsg |> dispatch) ]
              label [ ClassName "radio" ][str s]]
    let radioGroupItems = strList |> List.map stringToRadioGroupItem
    radioGroupItems
```
Notice the line:
```
OnClick (fun _ -> s  |> wrap |> onChangeMsg |> dispatch)
```
This way you will not need to use dynamic operators and you won't be needing to retrieve the `value` anymore from the `ev.target` because it is what you already provided from your model (and because the `value` doesn't change in a radio button as opposed a text input where using the value from `target` is necessary)

**Comment by ardave** [comment]
I definitely like that better.  I think maybe some copypasta from an `input type = "text"` elsewhere lulled me into using the dynamic operator in a place where it just wasn't necessary.

Thank you again for all of your help.
