### ISSUE TITLE
 Issue with Newtonsoft.Json with the newest DotnetClient verision 3.6

### ISSUE THREAD

**Issue by tforkmann** [Zaid-Ajaj/Fable.Remoting#180]
Hi Zaid,

we are getting a error message with the newest DotnetClient verision 3.4 .

Here the error message:

```
20.08.2020 00:00:00;Error;20.08.2020 14:10:24: Error - System.InvalidCastException: Cannot cast Newtonsoft.Json.Linq.JObject to Newtonsoft.Json.Linq.JToken.
   at Newtonsoft.Json.Linq.Extensions.Convert[T,U](T token)
   at Newtonsoft.Json.Linq.Extensions.Value[T,U](IEnumerable`1 value)
   at Fable.Remoting.Json.FableJsonConverter.ReadJson(JsonReader reader, Type t, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at <StartupCode$Fable-Remoting-Json>.$FableConverter.read@133(FableJsonConverter this, JsonSerializer serializer, JsonReader reader, Type[] itemTypes, Int32 index, FSharpList`1 acc)
   at Fable.Remoting.Json.FableJsonConverter.readElements(JsonReader reader, Type[] itemTypes, JsonSerializer serializer)
   at Fable.Remoting.Json.FableJsonConverter.ReadJson(JsonReader reader, Type t, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at <StartupCode$Fable-Remoting-Json>.$FableConverter.read@133(FableJsonConverter this, JsonSerializer serializer, JsonReader reader, Type[] itemTypes, Int32 index, FSharpList`1 acc)
   at Fable.Remoting.Json.FableJsonConverter.readElements(JsonReader reader, Type[] itemTypes, JsonSerializer serializer)
   at Fable.Remoting.Json.FableJsonConverter.ReadJson(JsonReader reader, Type t, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonConverter[] converters)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonConverter[] converters)
   at Fable.Remoting.DotnetClient.Proxy.safeProxyPost@47-5.Invoke(FSharpChoice`2 _arg2)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 417
   at Fable.Remoting.DotnetClient.Http.makePostRequest@32-4.Invoke(AsyncActivation`1 ctxt)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 109
--- End of stack trace from previous location where exception was thrown ---
   at FSharp.Control.Tasks.TaskBuilder.bindTaskConfigureFalse@131.Invoke(Unit unitVar0)
   at FSharp.Control.Tasks.TaskBuilder.tryWith[a](FSharpFunc`2 step, FSharpFunc`2 catch) - 00:00:00
```

Any idea why this happens?

Thanks in advance,

Tim

**Comment by Zaid-Ajaj** [comment]
Hi Tim,

I am not really sure why this happens, can you please provide more information about what types you are using for the data transport? 

Thanks

**Comment by kerams** [comment]
Weird, `JObject` is even a subclass of `JToken`.

**Comment by tforkmann** [comment]
Hi there,

my api type looks like this:

```fs
type Firmware =
    { Version: string }

```
```fs
type DataRecord =
    { TimeStamp: DateTimeOffset
      MeterId: Ids.RefDataField
      MeterType: Meter
      RowKey: Ids.SortableRowKey
      Value: float option
      ReadingError : ReadingError option }
```

```fs
type IDataExchangeApi =
    { ExchangeDataRecords: DateTime -> Async<DataRecord [] * Firmware>
      UpdateFirmware: Firmware -> Async<Firmware> }
```

I trie to exchange the data with cally the `callSafely` command

```fs
let proxy = Proxy.create<IDataExchangeApi> (routes plant.PiStaticIP)
let! result = proxy.callSafely <@ fun server -> server.ExchangeDataRecords(DateTime.UtcNow) @>
```

**Comment by Zaid-Ajaj** [comment]
@tforkmann Do you also have latest web server component? i.e. Fable.Remoting.Giraffe or similar

**Comment by tforkmann** [comment]
Just noticed I forgot to add the   `|> Remoting.withBinarySerialization` on the server side. Hope that helps. Not sure if it is mandatory for the Client.

**Comment by kerams** [comment]
And it's working? `Proxy.create<_>` creates a JSON serialization client proxy that can't be paired with the `withBinarySerialization` API. Looking at https://github.com/Zaid-Ajaj/Fable.Remoting/blob/master/Fable.Remoting.DotnetClient/Proxy.fs I don't think I've mixed it up...

**Comment by tforkmann** [comment]
Ok, after the `withBinarySerialization` Api I get following error msg:

```
20.08.2020 00:00:00;Error;20.08.2020 21:48:49: Error - Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: �. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonConverter[] converters)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonConverter[] converters)
   at Fable.Remoting.DotnetClient.Proxy.safeProxyPost@47-5.Invoke(FSharpChoice`2 _arg2)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 417
   at Fable.Remoting.DotnetClient.Http.makePostRequest@32-4.Invoke(AsyncActivation`1 ctxt)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 109
--- End of stack trace from previous location where exception was thrown ---
   at FSharp.Control.Tasks.TaskBuilder.bindTaskConfigureFalse@131.Invoke(Unit unitVar0)
   at FSharp.Control.Tasks.TaskBuilder.tryWith[a](FSharpFunc`2 step, FSharpFunc`2 catch) - 00:00:00
```

**Comment by Zaid-Ajaj** [comment]
@tforkmann How are creating the proxy? On the dotnet client you need 

let proxy = Proxy.create<IDataExchangeApi>(router xyz, isBinarySerialization=true)

That is if you are using withBinarySerialization on the server

**Comment by tforkmann** [comment]
Ahh nice!

Got it fixed with

```fs
let client = new HttpClient()
let getProxy ipAddress = Proxy.custom<IDataExchangeApi>(routes ipAddress) client true
```

Thanks for your help guys!

**Comment by MecuSorin** [comment]
I have the same symptom. Everything is up to date.

This is the request:
```
POST http://127.0.0.1:8185/api/IServerApi/command HTTP/1.1
Host: 127.0.0.1:8185
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtZSIsImp0aSI6IjI4ZTUxMGZhLWI4OWUtNGI0OC04MmFlLWYzYjg4YjExNTI3ZiIsIm5iZiI6MTU5ODI5NTcwMywiZXhwIjoxNTk4MzgyMTAzLCJpc3MiOiJoZXJvbml1cy5kZSIsImF1ZCI6Imhlcm9uaXVzLmRlIn0.UF0H5Eo42kCDF8dhDFiqRKJM6G2idSbDgYTSVtQOvMg
Content-Type: application/json; charset=utf-8
Content-Length: 241

[[{"CommandLabel":"Initializing programs"},{"IWantResponsesOn":{"ClientId":"dDY_ftBDlUWjemgjP6leWw"}},{"PositionSet":[{"Address":2},{"Cartesian":[{"x":0.0,"y":10.0,"z":6.0,"w":0.0,"p":0.0,"r":-90.0},{"CartesianConfig":"N U T, 0, 0, 0"}]}]}]]
```
and the response with full exception
```
HTTP/1.1 500 Internal Server Error
Date: Mon, 24 Aug 2020 19:01:44 GMT
Content-Type: application/json; charset=utf-8
Server: Kestrel
Content-Length: 3362

{"error":"Remoting error command System.InvalidCastException: Cannot cast Newtonsoft.Json.Linq.JObject to Newtonsoft.Json.Linq.JToken.\r\n   at Newtonsoft.Json.Linq.Extensions.Convert[T,U](T token)\r\n   at Newtonsoft.Json.Linq.Extensions.Value[T,U](IEnumerable`1 value)\r\n   at Fable.Remoting.Json.FableJsonConverter.ReadJson(JsonReader reader, Type t, Object existingValue, JsonSerializer serializer)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerProxy.DeserializeInternal(JsonReader reader, Type objectType)\r\n   at <StartupCode$Fable-Remoting-Json>.$FableConverter.read@133(FableJsonConverter this, JsonSerializer serializer, JsonReader reader, Type[] itemTypes, Int32 index, FSharpList`1 acc)\r\n   at Fable.Remoting.Json.FableJsonConverter.readElements(JsonReader reader, Type[] itemTypes, JsonSerializer serializer)\r\n   at Fable.Remoting.Json.FableJsonConverter.ReadJson(JsonReader reader, Type t, Object existingValue, JsonSerializer serializer)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerProxy.DeserializeInternal(JsonReader reader, Type objectType)\r\n   at <StartupCode$Fable-Remoting-Json>.$FableConverter.read@133(FableJsonConverter this, JsonSerializer serializer, JsonReader reader, Type[] itemTypes, Int32 index, FSharpList`1 acc)\r\n   at Fable.Remoting.Json.FableJsonConverter.readElements(JsonReader reader, Type[] itemTypes, JsonSerializer serializer)\r\n   at Fable.Remoting.Json.FableJsonConverter.ReadJson(JsonReader reader, Type t, Object existingValue, JsonSerializer serializer)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)\r\n   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)\r\n   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)\r\n   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)\r\n   at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)\r\n   at Fable.Remoting.Server.Proxy.makeEndpointProxy@89-17.Invoke(FSharpFunc`2 f, InvocationPropsInt props)\r\n   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1) in F:\\workspace\\_work\\1\\s\\src\\fsharp\\FSharp.Core\\async.fs:line 417\r\n   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in F:\\workspace\\_work\\1\\s\\src\\fsharp\\FSharp.Core\\async.fs:line 109","ignored":false,"handled":true}
```

Involved types:
```
type IServerApi =
        {
            command: CommandLabel * RequesterIdentifier * Requests.Command -> Async<OperationErrorMessage>
        }

type CommandLabel = CommandLabel of string
type ClientId = ClientId of string
type RobotIdToken = RobotId of string
type FeedbackChannelIfOutOfSync = FeedbackChannelIfOutOfSync of ClientId
type OperationErrorMessage = string option
type RequesterIdentifier =
        | IOwnRobot of RobotIdToken * FeedbackChannelIfOutOfSync
        | IWantResponsesOn of ClientId
type Address = Address of int
[<Struct>]
type CoordCartesian = {
        x: float
        y: float
        z: float
        w: float
        p: float
        r: float
    }
type CartesianConfig = CartesianConfig of string
type Position =
        | Cartesian of CoordCartesian * CartesianConfig
        | NotSet
[<RequireQualifiedAccess>]
module Requests 
        type Command =
            | PositionSet of Address * Position
            | RawCommand of string
```

I check if the binary serialization will do the trick for me, but didn't work either.

Any idea?

**Comment by Zaid-Ajaj** [comment]
Hi @MecuSorin, thanks a lot for the full repro, I will check it out shortly. In meantime please revert to the version you were using earlier until we fix the problem.

**Comment by Zaid-Ajaj** [comment]
@MecuSorin I was able to reproduce the problem and fix it in the Json deserialization component and updated everything downstream (DotnetClient v3.7.0 and server-side adapters) :smile: can you please give it a try and confirm that the problem actually is resolved? 

@tforkmann I believe this solves the original issue as well which was due to small bug when deserializing a union case that tuple of single unions

Please reopen the issue if the problem persists

**Comment by MecuSorin** [comment]
Great job Zaid! You rock! It works at least in the limited scope I can test at the moment.

**Comment by Zaid-Ajaj** [comment]
Great! If you find a more complicated use-case that doesn't work, just let me know!
